name: carnd-t3p2
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scipy
    - ffmpeg
    - imageio==2.1.1
    - pip:
        - moviepy
        - tensorflow==1.5

#envとしてconda env create -f ***.ymlで確保
#python==3.5　必須　　
#tensorflow==1.4でも？？　
#SSEの警告がでるが無視してよし
#.bashrcのパスは触らなくてよし（以下例ディフォルトのままで可能）
#export PYTHONPATH=~/miniconda3/lib/python3.6/site-packages:$PYTHONPATH
#export PATH="/home/kshiba/miniconda3/bin:$PATH"
